import type { SeedQuestion } from "./types";

/**
 * Vue interview flashcards derived from Challenge Lab challenge briefs.
 * Generated by scripts/import-challenge-lab-vue.ts — do not edit by hand.
 */
export const vueChallengeLabQuestions: SeedQuestion[] = [
  {
    id: "seed-q-lab-vue-01-counter",
    categorySlug: "vue",
    title: "Reactive Counter",
    content: `Complete the Counter component:
- Show the current count
- Buttons to increment, decrement, and reset to 0
- Decrement must not go below 0


Also open the app at /playground/counter to click around.`,
    explanation: `**Concepts:** ref, script setup, event handlers

1. Import \`ref\` from \`vue\`. Create \`const count = ref(0)\`.
2. In the template, use \`count\` (auto-unwrapped) and \`@click="count++"\`.`,
    difficulty: "BEGINNER",
    type: "FLASHCARD",
    tags: ["vue", "challenge-lab", "ref", "script setup", "event handlers"],
    answers: [
      {
        content: `Build a counter with ref() and the Composition API.`,
        isCorrect: true,
      },
    ],
  },
  {
    id: "seed-q-lab-vue-02-computed",
    categorySlug: "vue",
    title: "Computed Cart Total",
    content: `Complete the Cart component so \`itemCount\` and \`totalPrice\` are computed from \`items\`.`,
    explanation: `**Concepts:** computed, reactive arrays, derived state

1. \`computed(() => items.value.reduce(...))\` re-runs when items change.
2. Expose itemCount and totalPrice as computed refs.`,
    difficulty: "BEGINNER",
    type: "FLASHCARD",
    tags: ["vue", "challenge-lab", "computed", "reactive arrays", "derived state"],
    answers: [
      {
        content: `Derive values with computed() from a reactive list.`,
        isCorrect: true,
      },
    ],
  },
  {
    id: "seed-q-lab-vue-03-props-emits",
    categorySlug: "vue",
    title: "Props & Emits",
    content: `Complete Rating so it:
- Accepts \`modelValue\` (current rating) and optional \`max\` (default 5)
- Renders that many clickable stars
- Emits \`update:modelValue\` when a star is clicked`,
    explanation: `**Concepts:** defineProps, defineEmits, v-for

1. Use \`defineProps<{ modelValue: number; max?: number }>()\` and \`defineEmits<{ "update:modelValue": [value: number] }>()\`.
2. On star click, \`emit("update:modelValue", starNumber)\`.`,
    difficulty: "INTERMEDIATE",
    type: "FLASHCARD",
    tags: ["vue", "challenge-lab", "defineprops", "defineemits", "v-for"],
    answers: [
      {
        content: `Build a typed Rating star component with events.`,
        isCorrect: true,
      },
    ],
  },
  {
    id: "seed-q-lab-vue-04-watch",
    categorySlug: "vue",
    title: "Watchers",
    content: `Complete SearchBox so a \`watch\` on \`query\` calls \`props.onSearch(trimmed)\` when the trimmed query has at least 2 characters.

Do not debounce — tests assert right after each keystroke.`,
    explanation: `**Concepts:** watch, side effects, props

1. Inside the watcher, call \`props.onSearch(...)\` — \`onSearch\` is a prop, not a local name.
2. Trim first, then check length: \`const trimmed = value.trim()\`; only call when \`trimmed.length >= 2\`.
3. Pass the trimmed string to onSearch, not the \`query\` ref.`,
    difficulty: "INTERMEDIATE",
    type: "FLASHCARD",
    tags: ["vue", "challenge-lab", "watch", "side effects", "props"],
    answers: [
      {
        content: `React to state changes with watch.`,
        isCorrect: true,
      },
    ],
  },
  {
    id: "seed-q-lab-vue-05-composable",
    categorySlug: "vue",
    title: "Composable: useToggle",
    content: `Implement \`useToggle(initial = false)\` in the starter file.`,
    explanation: `**Concepts:** composables, ref, reuse

1. Return \`{ value, toggle, setTrue, setFalse }\` where value is a Ref<boolean>.
2. Composables are plain functions — no special Vue API beyond reactivity helpers.`,
    difficulty: "INTERMEDIATE",
    type: "FLASHCARD",
    tags: ["vue", "challenge-lab", "composables", "ref", "reuse"],
    answers: [
      {
        content: `Extract reusable reactive logic into a composable.`,
        isCorrect: true,
      },
    ],
  },
  {
    id: "seed-q-lab-vue-06-list",
    categorySlug: "vue",
    title: "Todo List App",
    content: `Build a working TodoApp:
- Add a todo from an input (Enter or button)
- Toggle completed
- Delete a todo
- Filter: All / Active / Done
- Show remaining active count


Playground: /playground/todos`,
    explanation: `**Concepts:** lists, v-model, computed filters, keys

1. Keep todos as \`ref<Todo[]>([])\`. Give each todo a unique id.
2. Filter with a computed that switches on \`filter\` (\`all\` | \`active\` | \`done\`).`,
    difficulty: "ADVANCED",
    type: "FLASHCARD",
    tags: ["vue", "challenge-lab", "lists", "v-model", "computed filters", "keys"],
    answers: [
      {
        content: `Capstone: add, toggle, filter, and remove todos.`,
        isCorrect: true,
      },
    ],
  },
  {
    id: "seed-q-lab-vue-07-define-model",
    categorySlug: "vue",
    title: "defineModel Text Field",
    content: `Complete TextField so a parent can use \`<TextField v-model="name" />\`.

- Use \`defineModel<string>\`
- Support optional \`label\` and \`placeholder\` props`,
    explanation: `**Concepts:** defineModel, v-model, props

1. \`const model = defineModel<string>({ required: true })\` replaces props + emit boilerplate.
2. In the template: \`<input v-model="model" />\`.`,
    difficulty: "BEGINNER",
    type: "FLASHCARD",
    tags: ["vue", "challenge-lab", "definemodel", "v-model", "props"],
    answers: [
      {
        content: `Build a reusable input with Vue 3.4 defineModel.`,
        isCorrect: true,
      },
    ],
  },
  {
    id: "seed-q-lab-vue-08-accordion",
    categorySlug: "vue",
    title: "Accordion (v-if)",
    content: `Complete Accordion:
- Only one panel body visible at a time
- Clicking the open header closes it
- Use \`v-if\` (not \`v-show\`) for the body`,
    explanation: `**Concepts:** v-if, ref, toggling UI

1. Store \`openId\` as \`ref<string | null>(null)\`.
2. Toggle: if \`openId === id\` set null, else set id. Template: \`v-if="openId === panel.id"\`.`,
    difficulty: "BEGINNER",
    type: "FLASHCARD",
    tags: ["vue", "challenge-lab", "v-if", "ref", "toggling ui"],
    answers: [
      {
        content: `Show one panel at a time with conditional rendering.`,
        isCorrect: true,
      },
    ],
  },
  {
    id: "seed-q-lab-vue-09-status-badge",
    categorySlug: "vue",
    title: "Dynamic Class & Style",
    content: `Complete StatusBadge:
- Apply \`badge-idle|loading|success|error\` from \`status\`
- Optional \`label\` overrides displayed text
- Optional \`color\` sets inline \`backgroundColor\``,
    explanation: `**Concepts:** :class, :style, computed

1. \`statusClass\` can return \`badge-\${status}\` or a map lookup.
2. For color override: \`computed(() => props.color ? { backgroundColor: props.color } : undefined)\`.`,
    difficulty: "BEGINNER",
    type: "FLASHCARD",
    tags: ["vue", "challenge-lab", ":class", ":style", "computed"],
    answers: [
      {
        content: `Bind CSS classes and inline styles from props.`,
        isCorrect: true,
      },
    ],
  },
  {
    id: "seed-q-lab-vue-10-auto-focus",
    categorySlug: "vue",
    title: "Template Refs",
    content: `Complete AutoFocus:
- Bind a template ref to the input
- Focus it on mount
- \`focus()\` focuses it again`,
    explanation: `**Concepts:** ref on DOM, onMounted, defineExpose

1. \`<input ref="inputEl" />\` with \`const inputEl = ref<HTMLInputElement | null>(null)\`.
2. \`onMounted(() => inputEl.value?.focus())\`.`,
    difficulty: "INTERMEDIATE",
    type: "FLASHCARD",
    tags: ["vue", "challenge-lab", "ref on dom", "onmounted", "defineexpose"],
    answers: [
      {
        content: `Focus an input with a template ref and onMounted.`,
        isCorrect: true,
      },
    ],
  },
  {
    id: "seed-q-lab-vue-11-provide-inject",
    categorySlug: "vue",
    title: "Provide / Inject Theme",
    content: `Complete ThemeSwitch:
- Root instances \`provide\` the theme ref
- Nested instances \`inject\` it and reflect changes
- Toggle flips light ↔ dark`,
    explanation: `**Concepts:** provide, inject, InjectionKey

1. When \`root\`, \`provide(themeKey, localTheme)\`.
2. Children \`inject(themeKey)\` and read \`.value\`. Toggle flips \`localTheme\` on the provider.`,
    difficulty: "INTERMEDIATE",
    type: "FLASHCARD",
    tags: ["vue", "challenge-lab", "provide", "inject", "injectionkey"],
    answers: [
      {
        content: `Share theme state down the tree without prop drilling.`,
        isCorrect: true,
      },
    ],
  },
  {
    id: "seed-q-lab-vue-12-slots",
    categorySlug: "vue",
    title: "Named Slots Card",
    content: `Complete SlotCard to render:
- Named \`header\` and \`footer\` (only when provided)
- Default slot in the body`,
    explanation: `**Concepts:** slots, named slots, $slots

1. \`<slot name="header" />\`, default \`<slot />\`, \`<slot name="footer" />\`.
2. Wrap header/footer with \`v-if="$slots.header"\` / \`$slots.footer\`.`,
    difficulty: "INTERMEDIATE",
    type: "FLASHCARD",
    tags: ["vue", "challenge-lab", "slots", "named slots", "$slots"],
    answers: [
      {
        content: `Compose layout with default and named slots.`,
        isCorrect: true,
      },
    ],
  },
  {
    id: "seed-q-lab-vue-13-lifecycle",
    categorySlug: "vue",
    title: "Load on Mount",
    content: `Complete UserLoader:
- Fetch on mount via the \`fetchUser\` prop
- Track \`loading\`, \`error\`, and \`user\`
- Reload button re-fetches`,
    explanation: `**Concepts:** onMounted, async, loading UI

1. Set \`loading = true\`, clear \`error\`, then \`try/catch\` around \`await fetchUser(userId)\`.
2. Call \`load()\` from \`onMounted\` and from the Reload button.`,
    difficulty: "INTERMEDIATE",
    type: "FLASHCARD",
    tags: ["vue", "challenge-lab", "onmounted", "async", "loading ui"],
    answers: [
      {
        content: `Fetch data in onMounted with loading and error states.`,
        isCorrect: true,
      },
    ],
  },
  {
    id: "seed-q-lab-vue-14-deep-watch",
    categorySlug: "vue",
    title: "Deep Watchers",
    content: `Complete DeepWatch so nested changes to \`profile\` append a log line.`,
    explanation: `**Concepts:** watch, deep, reactive

1. \`watch(profile, handler, { deep: true })\` — or watch a getter.
2. Push \`\`Changed: \${profile.name} @ \${profile.address.city}\`\` into \`logs\`.`,
    difficulty: "INTERMEDIATE",
    type: "FLASHCARD",
    tags: ["vue", "challenge-lab", "watch", "deep", "reactive"],
    answers: [
      {
        content: `Watch nested reactive objects with deep: true.`,
        isCorrect: true,
      },
    ],
  },
  {
    id: "seed-q-lab-vue-15-reactive-form",
    categorySlug: "vue",
    title: "Reactive Form Object",
    content: `Complete ReactiveForm:
- \`emailValid\` when email contains \`@\`
- \`canSubmit\` when name is non-empty and email is valid
- Reset clears both fields`,
    explanation: `**Concepts:** reactive, computed, v-model

1. \`emailValid\`: \`form.email.includes("@")\`.
2. \`canSubmit\`: name trimmed non-empty AND emailValid.`,
    difficulty: "INTERMEDIATE",
    type: "FLASHCARD",
    tags: ["vue", "challenge-lab", "reactive", "computed", "v-model"],
    answers: [
      {
        content: `Validate a reactive() form with computed flags.`,
        isCorrect: true,
      },
    ],
  },
  {
    id: "seed-q-lab-vue-16-checkbox-model",
    categorySlug: "vue",
    title: "Boolean defineModel",
    content: `Complete FancyCheckbox for \`<FancyCheckbox v-model="on" label="…" />\`.`,
    explanation: `**Concepts:** defineModel, checkbox, v-model

1. \`const checked = defineModel<boolean>({ default: false })\`.
2. \`<input type="checkbox" v-model="checked" />\`.`,
    difficulty: "BEGINNER",
    type: "FLASHCARD",
    tags: ["vue", "challenge-lab", "definemodel", "checkbox", "v-model"],
    answers: [
      {
        content: `Wire a checkbox with defineModel<boolean>.`,
        isCorrect: true,
      },
    ],
  },
  {
    id: "seed-q-lab-vue-17-teleport-modal",
    categorySlug: "vue",
    title: "Teleport Modal",
    content: `Complete Modal:
- Teleport overlay to \`body\` when \`open\`
- Emit \`close\` from backdrop and Close button
- Render default slot as content`,
    explanation: `**Concepts:** Teleport, emits, overlays

1. \`<Teleport to="body"><div v-if="open" …>\`
2. Backdrop and Close should \`emit("close")\`.`,
    difficulty: "INTERMEDIATE",
    type: "FLASHCARD",
    tags: ["vue", "challenge-lab", "teleport", "emits", "overlays"],
    answers: [
      {
        content: `Render a modal into document.body with Teleport.`,
        isCorrect: true,
      },
    ],
  },
  {
    id: "seed-q-lab-vue-18-transition",
    categorySlug: "vue",
    title: "Fade Transition",
    content: `Wrap the panel in \`<Transition name="fade">\` and show it with \`v-if="visible"\`.`,
    explanation: `**Concepts:** Transition, v-if, CSS transitions

1. \`<Transition name="fade"><div v-if="visible" …>\`
2. CSS classes \`.fade-enter-active\` etc. are already provided.`,
    difficulty: "INTERMEDIATE",
    type: "FLASHCARD",
    tags: ["vue", "challenge-lab", "transition", "v-if", "css transitions"],
    answers: [
      {
        content: `Animate enter/leave with <Transition>.`,
        isCorrect: true,
      },
    ],
  },
  {
    id: "seed-q-lab-vue-19-local-storage",
    categorySlug: "vue",
    title: "Composable: useLocalStorage",
    content: `Build \`useLocalStorage(key, initial)\` — a composable that makes any JSON-serializable value survive page reloads.

Why: components often need settings or drafts to persist. Instead of calling localStorage in every component, wrap it once (same idea as useToggle).

API example:
  const { value, clear } = useLocalStorage('theme', 'light')
  value.value = 'dark'   // also writes to localStorage
  clear()                // back to 'light', key removed

Behaviour:
1. Key missing in localStorage → start from \`initial\`
2. Key exists → JSON.parse it (if parse fails, use \`initial\`)
3. Whenever \`value\` changes → JSON.stringify + setItem
4. clear() → reset value to \`initial\`, then removeItem so the key is gone

Tips:
- Generic <T> so it works for numbers, strings, objects, …
- watch with { deep: true } so nested object edits are saved
- Prefer flush: 'sync' so the write happens immediately (not next tick)`,
    explanation: `**Concepts:** composables, ref, watch, JSON, generics

1. On create: \`const raw = localStorage.getItem(key)\`. If it’s null, use \`initial\`. Otherwise \`JSON.parse(raw)\` (fall back to \`initial\` if parse fails).
2. Create \`const value = ref(start)\` and \`watch(value, (v) => localStorage.setItem(key, JSON.stringify(v)), { deep: true, flush: "sync" })\`. \`deep\` covers objects; \`flush: "sync"\` writes immediately so tests (and callers) see storage right away.
3. \`clear()\`: set \`value.value = initial\` first (the watcher will rewrite storage), then \`localStorage.removeItem(key)\` so the key ends up deleted.`,
    difficulty: "ADVANCED",
    type: "FLASHCARD",
    tags: ["vue", "challenge-lab", "composables", "ref", "watch", "json", "generics"],
    answers: [
      {
        content: `Build a composable that keeps a ref in sync with localStorage across reloads.`,
        isCorrect: true,
      },
    ],
  },
  {
    id: "seed-q-lab-vue-20-notes",
    categorySlug: "vue",
    title: "Notes App",
    content: `Build NotesApp:
- Add note (non-empty title), clear drafts, select new note
- Edit title/body of selection in place
- Search filters list by title
- Delete selection and show empty state


Playground: /playground/notes`,
    explanation: `**Concepts:** lists, selection, computed filter, v-model

1. Keep notes in a ref array; \`selectedId\` points at the active note.
2. \`selected\` computed returns the note object so the editor can v-model its fields.
3. Filter with \`title.toLowerCase().includes(query.trim().toLowerCase())\`.`,
    difficulty: "ADVANCED",
    type: "FLASHCARD",
    tags: ["vue", "challenge-lab", "lists", "selection", "computed filter", "v-model"],
    answers: [
      {
        content: `Capstone: create, select, edit, search, and delete notes.`,
        isCorrect: true,
      },
    ],
  }
];
