import type { SeedChallenge } from "../challenge-types";

/**
 * Vue challenges imported from Challenge Lab (`../learning`).
 * Runner metadata lives in the `__meta__` test case.
 * Generated by scripts/import-challenge-lab-vue.ts — do not edit by hand.
 */
export const challengeLabVueChallenges: SeedChallenge[] = [
  {
    id: "seed-challenge-lab-vue-01-counter",
    categorySlug: "vue",
    title: "Reactive Counter",
    description: `Build a counter with ref() and the Composition API.

Complete the Counter component:
- Show the current count
- Buttons to increment, decrement, and reset to 0
- Decrement must not go below 0


Also open the app at /playground/counter to click around.`,
    difficulty: "BEGINNER",
    starterCode: `<script setup lang="ts">
/**
 * Challenge: Reactive Counter
 * - count starts at 0
 * - increment / decrement / reset
 * - decrement must not go below 0
 */
import { ref } from 'vue'

// TODO: create a reactive count
const count = ref(0)

function increment() {
  count.value++
  // TODO
}

function decrement() {
  count.value--
  // TODO: do not go below 0
}

function reset() {
  count.value = 0
  // TODO
}
</script>

<template>
  <div class="counter" data-testid="counter">
    <p class="count" data-testid="count">{{ count }}</p>
    <div class="actions">
      <button type="button" data-testid="dec" @click="decrement">−</button>
      <button type="button" data-testid="reset" @click="reset">Reset</button>
      <button type="button" data-testid="inc" @click="increment">+</button>
    </div>
  </div>
</template>

<style scoped>
.counter {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 1rem;
}
.count {
  font-family: var(--font-mono);
  font-size: 3rem;
  margin: 0;
  font-variant-numeric: tabular-nums;
}
.actions {
  display: flex;
  gap: 0.5rem;
}
button {
  font: inherit;
  padding: 0.5rem 1rem;
  cursor: pointer;
  border: 1px solid var(--border);
  background: var(--surface);
  color: var(--ink);
  border-radius: 6px;
}
button:hover {
  background: var(--surface-2);
}
</style>
`,
    solutionCode: `<script setup lang="ts">
import { ref } from 'vue'

const count = ref(0)

function increment() {
  count.value += 1
}

function decrement() {
  if (count.value > 0) count.value -= 1
}

function reset() {
  count.value = 0
}
</script>

<template>
  <div class="counter" data-testid="counter">
    <p class="count" data-testid="count">{{ count }}</p>
    <div class="actions">
      <button type="button" data-testid="dec" @click="decrement">−</button>
      <button type="button" data-testid="reset" @click="reset">Reset</button>
      <button type="button" data-testid="inc" @click="increment">+</button>
    </div>
  </div>
</template>
`,
    testCases: [
      {
        description: "__meta__",
        input: {
          runner: "vue",
          suiteId: "vue-01-counter",
          filename: "01-Counter.vue",
        },
        expectedOutput: true,
      },
    ],
    hints: [
      "Import `ref` from `vue`. Create `const count = ref(0)`.",
      "In the template, use `count` (auto-unwrapped) and `@click=\"count++\"`."
    ],
  },
  {
    id: "seed-challenge-lab-vue-02-computed",
    categorySlug: "vue",
    title: "Computed Cart Total",
    description: `Derive values with computed() from a reactive list.

Complete the Cart component so \`itemCount\` and \`totalPrice\` are computed from \`items\`.`,
    difficulty: "BEGINNER",
    starterCode: `<script setup lang="ts">
/**
 * Challenge: Computed Cart Total
 */
import { ref, computed } from 'vue'

export interface CartItem {
  id: string
  name: string
  price: number
  qty: number
}

const items = ref<CartItem[]>([
  { id: '1', name: 'Notebook', price: 12, qty: 2 },
  { id: '2', name: 'Pen', price: 3, qty: 5 },
])

// TODO: derived from items — total number of units (sum of qty)
const itemCount = computed(() => 0)

// TODO: sum of price * qty for every item
const totalPrice = computed(() => 0)

function addItem() {
  items.value.push({
    id: String(Date.now()),
    name: 'Sticker',
    price: 2,
    qty: 1,
  })
}

defineExpose({ items, itemCount, totalPrice, addItem })
</script>

<template>
  <div class="cart" data-testid="cart">
    <ul>
      <li v-for="item in items" :key="item.id">
        {{ item.name }} × {{ item.qty }} — \${{ item.price * item.qty }}
      </li>
    </ul>
    <p data-testid="count">Items: {{ itemCount }}</p>
    <p data-testid="total">Total: \${{ totalPrice }}</p>
    <button type="button" data-testid="add" @click="addItem">Add sticker</button>
  </div>
</template>
`,
    solutionCode: `/*
In src/challenges/vue/02-Cart.vue replace the computed stubs with:

const itemCount = computed(() =>
  items.value.reduce((sum, item) => sum + item.qty, 0),
)

const totalPrice = computed(() =>
  items.value.reduce((sum, item) => sum + item.price * item.qty, 0),
)
*/
export {}
`,
    testCases: [
      {
        description: "__meta__",
        input: {
          runner: "vue",
          suiteId: "vue-02-computed",
          filename: "02-Cart.vue",
        },
        expectedOutput: true,
      },
    ],
    hints: [
      "`computed(() => items.value.reduce(...))` re-runs when items change.",
      "Expose itemCount and totalPrice as computed refs."
    ],
  },
  {
    id: "seed-challenge-lab-vue-03-props-emits",
    categorySlug: "vue",
    title: "Props & Emits",
    description: `Build a typed Rating star component with events.

Complete Rating so it:
- Accepts \`modelValue\` (current rating) and optional \`max\` (default 5)
- Renders that many clickable stars
- Emits \`update:modelValue\` when a star is clicked`,
    difficulty: "INTERMEDIATE",
    starterCode: `<script setup lang="ts">
/**
 * Challenge: Props & Emits — Rating stars
 */
import { computed } from 'vue'

const props = withDefaults(
  defineProps<{
    modelValue: number
    max?: number
  }>(),
  { max: 5 },
)

const emit = defineEmits<{
  'update:modelValue': [value: number]
}>()

const stars = computed(() => Array.from({ length: props.max }, (_, i) => i + 1))

function select(value: number) {
  // TODO: emit update:modelValue
  void value
}
</script>

<template>
  <div class="rating" data-testid="rating" role="group" :aria-label="\`Rating \${modelValue} of \${max}\`">
    <button
      v-for="star in stars"
      :key="star"
      type="button"
      class="star"
      :data-testid="\`star-\${star}\`"
      :aria-pressed="star <= modelValue"
      :class="{ active: star <= modelValue }"
      @click="select(star)"
    >
      ★
    </button>
  </div>
</template>

<style scoped>
.rating {
  display: inline-flex;
  gap: 0.15rem;
}
.star {
  font-size: 1.5rem;
  border: none;
  background: transparent;
  cursor: pointer;
  color: #c4b8a8;
  padding: 0.1rem;
  line-height: 1;
}
.star.active {
  color: #d97706;
}
</style>
`,
    solutionCode: `// In select():
// emit('update:modelValue', value)
`,
    testCases: [
      {
        description: "__meta__",
        input: {
          runner: "vue",
          suiteId: "vue-03-props-emits",
          filename: "03-Rating.vue",
        },
        expectedOutput: true,
      },
    ],
    hints: [
      "Use `defineProps<{ modelValue: number; max?: number }>()` and `defineEmits<{ \"update:modelValue\": [value: number] }>()`.",
      "On star click, `emit(\"update:modelValue\", starNumber)`."
    ],
  },
  {
    id: "seed-challenge-lab-vue-04-watch",
    categorySlug: "vue",
    title: "Watchers",
    description: `React to state changes with watch.

Complete SearchBox so a \`watch\` on \`query\` calls \`props.onSearch(trimmed)\` when the trimmed query has at least 2 characters.

Do not debounce — tests assert right after each keystroke.`,
    difficulty: "INTERMEDIATE",
    starterCode: `<script setup lang="ts">
/**
 * Challenge: Watchers — SearchBox
 * When \`query\` changes and trimmed length >= 2, call props.onSearch(trimmed).
 */
import { ref, watch } from 'vue'

const props = defineProps<{
  onSearch: (q: string) => void
}>()

const query = ref('')

// TODO: watch query and call props.onSearch when trimmed length >= 2
watch(
  query,
  (value) => {
    void value
    void props
  },
)

defineExpose({ query })
</script>

<template>
  <div class="search">
    <label>
      Search
      <input
        v-model="query"
        data-testid="input"
        type="search"
        placeholder="Type at least 2 characters…"
      />
    </label>
  </div>
</template>
`,
    solutionCode: `// Replace the watch callback body in 04-SearchBox.vue:
//
// watch(query, (value) => {
//   const trimmed = value.trim()
//   if (trimmed.length >= 2) props.onSearch(trimmed)
// })
`,
    testCases: [
      {
        description: "__meta__",
        input: {
          runner: "vue",
          suiteId: "vue-04-watch",
          filename: "04-SearchBox.vue",
        },
        expectedOutput: true,
      },
    ],
    hints: [
      "Inside the watcher, call `props.onSearch(...)` — `onSearch` is a prop, not a local name.",
      "Trim first, then check length: `const trimmed = value.trim()`; only call when `trimmed.length >= 2`.",
      "Pass the trimmed string to onSearch, not the `query` ref."
    ],
  },
  {
    id: "seed-challenge-lab-vue-05-composable",
    categorySlug: "vue",
    title: "Composable: useToggle",
    description: `Extract reusable reactive logic into a composable.

Implement \`useToggle(initial = false)\` in the starter file.`,
    difficulty: "INTERMEDIATE",
    starterCode: `import { ref, type Ref } from 'vue'

/**
 * Challenge: useToggle composable
 * Return a boolean ref plus helpers to flip / force true / force false.
 */
export function useToggle(initial = false): {
  value: Ref<boolean>
  toggle: () => void
  setTrue: () => void
  setFalse: () => void
} {
  // TODO: implement
  void ref
  void initial
  throw new Error('Not implemented')
}
`,
    solutionCode: `import { ref, type Ref } from 'vue'

export function useToggle(initial = false): {
  value: Ref<boolean>
  toggle: () => void
  setTrue: () => void
  setFalse: () => void
} {
  const value = ref(initial)
  return {
    value,
    toggle: () => {
      value.value = !value.value
    },
    setTrue: () => {
      value.value = true
    },
    setFalse: () => {
      value.value = false
    },
  }
}
`,
    testCases: [
      {
        description: "__meta__",
        input: {
          runner: "vue",
          suiteId: "vue-05-composable",
          filename: "05-useToggle.ts",
        },
        expectedOutput: true,
      },
    ],
    hints: [
      "Return `{ value, toggle, setTrue, setFalse }` where value is a Ref<boolean>.",
      "Composables are plain functions — no special Vue API beyond reactivity helpers."
    ],
  },
  {
    id: "seed-challenge-lab-vue-06-list",
    categorySlug: "vue",
    title: "Todo List App",
    description: `Capstone: add, toggle, filter, and remove todos.

Build a working TodoApp:
- Add a todo from an input (Enter or button)
- Toggle completed
- Delete a todo
- Filter: All / Active / Done
- Show remaining active count


Playground: /playground/todos`,
    difficulty: "ADVANCED",
    starterCode: `<script setup lang="ts">
/**
 * Challenge: Todo List App (capstone)
 *
 * Requirements:
 * - Add todo from input (button or Enter), clear input after add
 * - Ignore empty / whitespace-only input
 * - Toggle completed on checkbox
 * - Delete a todo
 * - Filter: all | active | done
 * - Show count of remaining (not completed) todos
 */
import { ref, computed } from 'vue'

export interface Todo {
  id: number
  text: string
  done: boolean
}

type Filter = 'all' | 'active' | 'done'

const todos = ref<Todo[]>([])
const draft = ref('')
const filter = ref<Filter>('all')

let nextId = 1

const visible = computed((): Todo[] => {
  // TODO: filter todos based on filter.value
  return todos.value
})

const remaining = computed(() => {
  // TODO: count todos where done === false
  return 0
})

function addTodo() {
  // TODO: push { id: nextId++, text: draft trimmed, done: false }, then clear draft
  void nextId
}

function toggleTodo(id: number) {
  // TODO
  void id
}

function removeTodo(id: number) {
  // TODO
  void id
}

defineExpose({ todos, draft, filter, visible, remaining, addTodo, toggleTodo, removeTodo })
</script>

<template>
  <div class="todo-app" data-testid="todo-app">
    <form
      @submit.prevent="addTodo"
      class="add-row"
    >
      <input
        v-model="draft"
        data-testid="input"
        type="text"
        placeholder="What needs doing?"
        aria-label="New todo"
      />
      <button type="submit" data-testid="add">Add</button>
    </form>

    <div class="filters" role="tablist">
      <button
        type="button"
        data-testid="filter-all"
        :class="{ active: filter === 'all' }"
        @click="filter = 'all'"
      >
        All
      </button>
      <button
        type="button"
        data-testid="filter-active"
        :class="{ active: filter === 'active' }"
        @click="filter = 'active'"
      >
        Active
      </button>
      <button
        type="button"
        data-testid="filter-done"
        :class="{ active: filter === 'done' }"
        @click="filter = 'done'"
      >
        Done
      </button>
    </div>

    <ul data-testid="list">
      <li
        v-for="todo in visible"
        :key="todo.id"
        :data-testid="\`todo-\${todo.id}\`"
        :class="{ done: todo.done }"
      >
        <label>
          <input
            type="checkbox"
            :checked="todo.done"
            :data-testid="\`toggle-\${todo.id}\`"
            @change="toggleTodo(todo.id)"
          />
          <span>{{ todo.text }}</span>
        </label>
        <button
          type="button"
          :data-testid="\`remove-\${todo.id}\`"
          @click="removeTodo(todo.id)"
        >
          Delete
        </button>
      </li>
    </ul>

    <p class="remaining" data-testid="remaining">{{ remaining }} left</p>
  </div>
</template>

<style scoped>
.todo-app {
  display: flex;
  flex-direction: column;
  gap: 1rem;
  max-width: 28rem;
}
.add-row {
  display: flex;
  gap: 0.5rem;
}
.add-row input {
  flex: 1;
  font: inherit;
  padding: 0.55rem 0.75rem;
  border: 1px solid var(--border);
  border-radius: 6px;
  background: var(--surface);
  color: var(--ink);
}
.filters {
  display: flex;
  gap: 0.35rem;
}
.filters button,
button {
  font: inherit;
  padding: 0.4rem 0.75rem;
  border: 1px solid var(--border);
  border-radius: 6px;
  background: var(--surface);
  color: var(--ink);
  cursor: pointer;
}
.filters button.active {
  background: var(--ink);
  color: var(--paper);
  border-color: var(--ink);
}
ul {
  list-style: none;
  margin: 0;
  padding: 0;
  display: flex;
  flex-direction: column;
  gap: 0.4rem;
}
li {
  display: flex;
  justify-content: space-between;
  align-items: center;
  gap: 0.75rem;
  padding: 0.5rem 0;
  border-bottom: 1px solid var(--border);
}
li.done span {
  text-decoration: line-through;
  opacity: 0.55;
}
label {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  cursor: pointer;
}
.remaining {
  margin: 0;
  font-size: 0.9rem;
  color: var(--muted);
}
</style>
`,
    solutionCode: `/*
TodoApp solution sketch — paste into the <script setup> of 06-TodoApp.vue:

const visible = computed(() => {
  if (filter.value === 'active') return todos.value.filter((t) => !t.done)
  if (filter.value === 'done') return todos.value.filter((t) => t.done)
  return todos.value
})

const remaining = computed(() => todos.value.filter((t) => !t.done).length)

function addTodo() {
  const text = draft.value.trim()
  if (!text) return
  todos.value.push({ id: nextId++, text, done: false })
  draft.value = ''
}

function toggleTodo(id: number) {
  const todo = todos.value.find((t) => t.id === id)
  if (todo) todo.done = !todo.done
}

function removeTodo(id: number) {
  todos.value = todos.value.filter((t) => t.id !== id)
}
*/
export {}
`,
    testCases: [
      {
        description: "__meta__",
        input: {
          runner: "vue",
          suiteId: "vue-06-list",
          filename: "06-TodoApp.vue",
        },
        expectedOutput: true,
      },
    ],
    hints: [
      "Keep todos as `ref<Todo[]>([])`. Give each todo a unique id.",
      "Filter with a computed that switches on `filter` (`all` | `active` | `done`)."
    ],
  },
  {
    id: "seed-challenge-lab-vue-07-define-model",
    categorySlug: "vue",
    title: "defineModel Text Field",
    description: `Build a reusable input with Vue 3.4 defineModel.

Complete TextField so a parent can use \`<TextField v-model="name" />\`.

- Use \`defineModel<string>\`
- Support optional \`label\` and \`placeholder\` props`,
    difficulty: "BEGINNER",
    starterCode: `<script setup lang="ts">
/**
 * Challenge: Custom v-model with defineModel
 * - Bind an input to a parent via v-model
 * - Optional label and placeholder props
 */
// TODO: const model = defineModel<string>({ required: true })

defineProps<{
  label?: string
  placeholder?: string
}>()
</script>

<template>
  <label class="field" data-testid="field">
    <span v-if="label" class="label">{{ label }}</span>
    <!-- TODO: <input v-model="model" data-testid="input" … /> -->
    <input
      data-testid="input"
      type="text"
      :placeholder="placeholder ?? ''"
    />
  </label>
</template>

<style scoped>
.field {
  display: flex;
  flex-direction: column;
  gap: 0.35rem;
  font: inherit;
}
.label {
  font-size: 0.85rem;
  color: var(--muted);
}
input {
  font: inherit;
  padding: 0.55rem 0.75rem;
  border: 1px solid var(--border);
  border-radius: 6px;
  background: var(--surface);
  color: var(--ink);
}
</style>
`,
    solutionCode: `<script setup lang="ts">
/**
 * Solution: Custom v-model with defineModel
 */
const model = defineModel<string>({ required: true })

defineProps<{
  label?: string
  placeholder?: string
}>()
</script>

<template>
  <label class="field" data-testid="field">
    <span v-if="label" class="label">{{ label }}</span>
    <input
      v-model="model"
      data-testid="input"
      type="text"
      :placeholder="placeholder ?? ''"
    />
  </label>
</template>

<style scoped>
.field {
  display: flex;
  flex-direction: column;
  gap: 0.35rem;
  font: inherit;
}
.label {
  font-size: 0.85rem;
  color: var(--muted);
}
input {
  font: inherit;
  padding: 0.55rem 0.75rem;
  border: 1px solid var(--border);
  border-radius: 6px;
  background: var(--surface);
  color: var(--ink);
}
</style>
`,
    testCases: [
      {
        description: "__meta__",
        input: {
          runner: "vue",
          suiteId: "vue-07-define-model",
          filename: "07-TextField.vue",
        },
        expectedOutput: true,
      },
    ],
    hints: [
      "`const model = defineModel<string>({ required: true })` replaces props + emit boilerplate.",
      "In the template: `<input v-model=\"model\" />`."
    ],
  },
  {
    id: "seed-challenge-lab-vue-08-accordion",
    categorySlug: "vue",
    title: "Accordion (v-if)",
    description: `Show one panel at a time with conditional rendering.

Complete Accordion:
- Only one panel body visible at a time
- Clicking the open header closes it
- Use \`v-if\` (not \`v-show\`) for the body`,
    difficulty: "BEGINNER",
    starterCode: `<script setup lang="ts">
/**
 * Challenge: Conditional rendering (v-if / v-show)
 * - Only one panel open at a time
 * - Clicking the open panel's header closes it
 */
import { ref } from 'vue'

export interface Panel {
  id: string
  title: string
  body: string
}

defineProps<{
  panels: Panel[]
}>()

// TODO: track which panel id is open (null when all closed)
const openId = ref<string | null>(null)

function toggle(id: string) {
  // TODO: if already open, close; otherwise open this id
  void id
}

defineExpose({ openId, toggle })
</script>

<template>
  <div class="accordion" data-testid="accordion">
    <section v-for="panel in panels" :key="panel.id" class="panel">
      <button
        type="button"
        class="header"
        :data-testid="\`header-\${panel.id}\`"
        :aria-expanded="openId === panel.id"
        @click="toggle(panel.id)"
      >
        {{ panel.title }}
      </button>
      <!-- Show body only when this panel is open -->
      <div
        v-if="openId === panel.id"
        class="body"
        :data-testid="\`body-\${panel.id}\`"
      >
        {{ panel.body }}
      </div>
    </section>
  </div>
</template>

<style scoped>
.accordion {
  display: flex;
  flex-direction: column;
  gap: 0.35rem;
  max-width: 28rem;
}
.header {
  width: 100%;
  text-align: left;
  font: inherit;
  padding: 0.65rem 0.85rem;
  border: 1px solid var(--border);
  border-radius: 6px;
  background: var(--surface);
  color: var(--ink);
  cursor: pointer;
}
.body {
  padding: 0.75rem 0.85rem;
  color: var(--muted);
  font-size: 0.95rem;
}
</style>
`,
    solutionCode: `/** Solution sketch — Accordion toggle + v-if */
const openId = ref<string | null>(null)

function toggle(id: string) {
  openId.value = openId.value === id ? null : id
}

// template: v-if="openId === panel.id"
`,
    testCases: [
      {
        description: "__meta__",
        input: {
          runner: "vue",
          suiteId: "vue-08-accordion",
          filename: "08-Accordion.vue",
        },
        expectedOutput: true,
      },
    ],
    hints: [
      "Store `openId` as `ref<string | null>(null)`.",
      "Toggle: if `openId === id` set null, else set id. Template: `v-if=\"openId === panel.id\"`."
    ],
  },
  {
    id: "seed-challenge-lab-vue-09-status-badge",
    categorySlug: "vue",
    title: "Dynamic Class & Style",
    description: `Bind CSS classes and inline styles from props.

Complete StatusBadge:
- Apply \`badge-idle|loading|success|error\` from \`status\`
- Optional \`label\` overrides displayed text
- Optional \`color\` sets inline \`backgroundColor\``,
    difficulty: "BEGINNER",
    starterCode: `<script setup lang="ts">
/**
 * Challenge: Dynamic class & style bindings
 * - Map status → CSS class name
 * - Optional inline style for a custom color override
 */
import { computed } from 'vue'

export type Status = 'idle' | 'loading' | 'success' | 'error'

const props = defineProps<{
  status: Status
  label?: string
  /** When set, use as the badge background color */
  color?: string
}>()

// TODO: map status to class: idle→badge-idle, loading→badge-loading, etc.
const statusClass = computed(() => {
  void props.status
  return ''
})

// TODO: if color prop set, return { backgroundColor: color }, else undefined
const overrideStyle = computed(() => {
  void props.color
  return undefined as undefined | { backgroundColor: string }
})

const text = computed(() => props.label ?? props.status)
</script>

<template>
  <span
    class="badge"
    data-testid="badge"
    :class="statusClass"
    :style="overrideStyle"
  >
    {{ text }}
  </span>
</template>

<style scoped>
.badge {
  display: inline-block;
  padding: 0.25rem 0.65rem;
  border-radius: 999px;
  font-size: 0.8rem;
  font-weight: 600;
  text-transform: capitalize;
  background: #e5e5e5;
  color: #171717;
}
.badge-idle {
  background: #e5e5e5;
}
.badge-loading {
  background: #dbeafe;
  color: #1e40af;
}
.badge-success {
  background: #dcfce7;
  color: #166534;
}
.badge-error {
  background: #fee2e2;
  color: #991b1b;
}
</style>
`,
    solutionCode: `/** Solution sketch — StatusBadge */
const statusClass = computed(() => \`badge-\${props.status}\`)

const overrideStyle = computed(() =>
  props.color ? { backgroundColor: props.color } : undefined,
)
`,
    testCases: [
      {
        description: "__meta__",
        input: {
          runner: "vue",
          suiteId: "vue-09-status-badge",
          filename: "09-StatusBadge.vue",
        },
        expectedOutput: true,
      },
    ],
    hints: [
      "`statusClass` can return `badge-${status}` or a map lookup.",
      "For color override: `computed(() => props.color ? { backgroundColor: props.color } : undefined)`."
    ],
  },
  {
    id: "seed-challenge-lab-vue-10-auto-focus",
    categorySlug: "vue",
    title: "Template Refs",
    description: `Focus an input with a template ref and onMounted.

Complete AutoFocus:
- Bind a template ref to the input
- Focus it on mount
- \`focus()\` focuses it again`,
    difficulty: "INTERMEDIATE",
    starterCode: `<script setup lang="ts">
/**
 * Challenge: Template refs + onMounted
 * - Grab the input via a template ref
 * - Focus it when the component mounts
 * - Expose a focus() method that focuses again
 */
import { ref, onMounted } from 'vue'

const inputEl = ref<HTMLInputElement | null>(null)

onMounted(() => {
  // TODO: focus the input
})

function focus() {
  // TODO: focus inputEl
}

defineExpose({ inputEl, focus })
</script>

<template>
  <div class="auto-focus" data-testid="auto-focus">
    <label>
      Quick search
      <!-- TODO: bind ref="inputEl" -->
      <input data-testid="input" type="search" placeholder="Focus me…" />
    </label>
    <button type="button" data-testid="refocus" @click="focus">Focus</button>
  </div>
</template>

<style scoped>
.auto-focus {
  display: flex;
  flex-direction: column;
  gap: 0.75rem;
  align-items: flex-start;
}
label {
  display: flex;
  flex-direction: column;
  gap: 0.35rem;
  font-size: 0.85rem;
  color: var(--muted);
}
input {
  font: inherit;
  padding: 0.55rem 0.75rem;
  border: 1px solid var(--border);
  border-radius: 6px;
  background: var(--surface);
  color: var(--ink);
}
button {
  font: inherit;
  padding: 0.4rem 0.75rem;
  border: 1px solid var(--border);
  border-radius: 6px;
  background: var(--surface);
  color: var(--ink);
  cursor: pointer;
}
</style>
`,
    solutionCode: `/** Solution sketch — AutoFocus */
const inputEl = ref<HTMLInputElement | null>(null)

onMounted(() => {
  inputEl.value?.focus()
})

function focus() {
  inputEl.value?.focus()
}

// template: <input ref="inputEl" … />
`,
    testCases: [
      {
        description: "__meta__",
        input: {
          runner: "vue",
          suiteId: "vue-10-auto-focus",
          filename: "10-AutoFocus.vue",
        },
        expectedOutput: true,
      },
    ],
    hints: [
      "`<input ref=\"inputEl\" />` with `const inputEl = ref<HTMLInputElement | null>(null)`.",
      "`onMounted(() => inputEl.value?.focus())`."
    ],
  },
  {
    id: "seed-challenge-lab-vue-11-provide-inject",
    categorySlug: "vue",
    title: "Provide / Inject Theme",
    description: `Share theme state down the tree without prop drilling.

Complete ThemeSwitch:
- Root instances \`provide\` the theme ref
- Nested instances \`inject\` it and reflect changes
- Toggle flips light ↔ dark`,
    difficulty: "INTERMEDIATE",
    starterCode: `<script lang="ts">
import type { InjectionKey, Ref } from 'vue'

export type Theme = 'light' | 'dark'
export const themeKey: InjectionKey<Ref<Theme>> = Symbol('theme')
</script>

<script setup lang="ts">
/**
 * Challenge: provide / inject — theme context
 * Parent provides theme; child injects and applies it.
 */
import { provide, inject, ref, computed } from 'vue'

const props = defineProps<{
  /** When true, this instance is the provider (root). */
  root?: boolean
  initial?: Theme
}>()

const localTheme = ref<Theme>(props.initial ?? 'light')

if (props.root) {
  // TODO: provide(themeKey, localTheme)
  void provide
  void themeKey
}

// TODO: inject theme (required when not root). Fallback to localTheme for root.
const theme = computed(() => {
  if (props.root) return localTheme.value
  const injected = inject(themeKey, null)
  void injected
  return 'light' as Theme
})

function toggle() {
  // TODO: flip light ↔ dark on the provided/local ref
}

defineExpose({ theme, localTheme, toggle })
</script>

<template>
  <div
    class="theme-box"
    data-testid="theme-box"
    :data-theme="theme"
    :class="theme"
  >
    <p data-testid="label">Theme: {{ theme }}</p>
    <button v-if="root" type="button" data-testid="toggle" @click="toggle">
      Toggle theme
    </button>
    <div v-if="$slots.default" class="children">
      <slot />
    </div>
  </div>
</template>

<style scoped>
.theme-box {
  padding: 1rem;
  border-radius: 8px;
  border: 1px solid var(--border);
}
.theme-box.light {
  background: #fafafa;
  color: #171717;
}
.theme-box.dark {
  background: #171717;
  color: #fafafa;
}
.children {
  margin-top: 0.75rem;
}
button {
  font: inherit;
  padding: 0.4rem 0.75rem;
  border: 1px solid currentColor;
  border-radius: 6px;
  background: transparent;
  color: inherit;
  cursor: pointer;
}
</style>
`,
    solutionCode: `/** Solution sketch — ThemeSwitch provide/inject */
if (props.root) {
  provide(themeKey, localTheme)
}

const themeRef = props.root ? localTheme : inject(themeKey, localTheme)

const theme = computed(() => themeRef.value)

function toggle() {
  localTheme.value = localTheme.value === 'light' ? 'dark' : 'light'
}
`,
    testCases: [
      {
        description: "__meta__",
        input: {
          runner: "vue",
          suiteId: "vue-11-provide-inject",
          filename: "11-ThemeSwitch.vue",
        },
        expectedOutput: true,
      },
    ],
    hints: [
      "When `root`, `provide(themeKey, localTheme)`.",
      "Children `inject(themeKey)` and read `.value`. Toggle flips `localTheme` on the provider."
    ],
  },
  {
    id: "seed-challenge-lab-vue-12-slots",
    categorySlug: "vue",
    title: "Named Slots Card",
    description: `Compose layout with default and named slots.

Complete SlotCard to render:
- Named \`header\` and \`footer\` (only when provided)
- Default slot in the body`,
    difficulty: "INTERMEDIATE",
    starterCode: `<script setup lang="ts">
/**
 * Challenge: Named & default slots
 * Render header / default / footer slot outlets.
 */
// No script logic required — fill in the template slots.
</script>

<template>
  <article class="card" data-testid="card">
    <!-- TODO: if $slots.header, render <header data-testid="header"><slot name="header" /></header> -->
    <!-- TODO: <div data-testid="body"><slot /></div> -->
    <!-- TODO: if $slots.footer, render <footer data-testid="footer"><slot name="footer" /></footer> -->
  </article>
</template>

<style scoped>
.card {
  border: 1px solid var(--border);
  border-radius: 10px;
  background: var(--surface);
  overflow: hidden;
  max-width: 24rem;
}
.card-header {
  padding: 0.75rem 1rem;
  border-bottom: 1px solid var(--border);
  font-weight: 600;
}
.card-body {
  padding: 1rem;
}
.card-footer {
  padding: 0.75rem 1rem;
  border-top: 1px solid var(--border);
  font-size: 0.85rem;
  color: var(--muted);
}
</style>
`,
    solutionCode: `<!-- Solution sketch — SlotCard template -->
<template>
  <article class="card" data-testid="card">
    <header v-if="$slots.header" class="card-header" data-testid="header">
      <slot name="header" />
    </header>
    <div class="card-body" data-testid="body">
      <slot />
    </div>
    <footer v-if="$slots.footer" class="card-footer" data-testid="footer">
      <slot name="footer" />
    </footer>
  </article>
</template>
`,
    testCases: [
      {
        description: "__meta__",
        input: {
          runner: "vue",
          suiteId: "vue-12-slots",
          filename: "12-SlotCard.vue",
        },
        expectedOutput: true,
      },
    ],
    hints: [
      "`<slot name=\"header\" />`, default `<slot />`, `<slot name=\"footer\" />`.",
      "Wrap header/footer with `v-if=\"$slots.header\"` / `$slots.footer`."
    ],
  },
  {
    id: "seed-challenge-lab-vue-13-lifecycle",
    categorySlug: "vue",
    title: "Load on Mount",
    description: `Fetch data in onMounted with loading and error states.

Complete UserLoader:
- Fetch on mount via the \`fetchUser\` prop
- Track \`loading\`, \`error\`, and \`user\`
- Reload button re-fetches`,
    difficulty: "INTERMEDIATE",
    starterCode: `<script setup lang="ts">
/**
 * Challenge: Lifecycle — load data on mount
 * - Call fetchUser(id) inside onMounted
 * - Track loading / error / user state
 */
import { ref, onMounted } from 'vue'

export interface User {
  id: number
  name: string
  email: string
}

const props = defineProps<{
  userId: number
  fetchUser: (id: number) => Promise<User>
}>()

const user = ref<User | null>(null)
const loading = ref(false)
const error = ref<string | null>(null)

async function load() {
  // TODO: set loading true, clear error, await fetchUser, set user or error
  void props
}

onMounted(() => {
  // TODO: call load()
})

defineExpose({ user, loading, error, load })
</script>

<template>
  <div class="loader" data-testid="loader">
    <p v-if="loading" data-testid="loading">Loading…</p>
    <p v-else-if="error" data-testid="error">{{ error }}</p>
    <div v-else-if="user" data-testid="user">
      <p data-testid="name">{{ user.name }}</p>
      <p data-testid="email">{{ user.email }}</p>
    </div>
    <p v-else data-testid="empty">No user</p>
    <button type="button" data-testid="reload" @click="load">Reload</button>
  </div>
</template>

<style scoped>
.loader {
  display: flex;
  flex-direction: column;
  gap: 0.5rem;
}
button {
  align-self: flex-start;
  font: inherit;
  padding: 0.4rem 0.75rem;
  border: 1px solid var(--border);
  border-radius: 6px;
  background: var(--surface);
  color: var(--ink);
  cursor: pointer;
}
</style>
`,
    solutionCode: `/** Solution sketch — UserLoader */
async function load() {
  loading.value = true
  error.value = null
  try {
    user.value = await props.fetchUser(props.userId)
  } catch (e) {
    error.value = e instanceof Error ? e.message : String(e)
    user.value = null
  } finally {
    loading.value = false
  }
}

onMounted(() => {
  void load()
})
`,
    testCases: [
      {
        description: "__meta__",
        input: {
          runner: "vue",
          suiteId: "vue-13-lifecycle",
          filename: "13-UserLoader.vue",
        },
        expectedOutput: true,
      },
    ],
    hints: [
      "Set `loading = true`, clear `error`, then `try/catch` around `await fetchUser(userId)`.",
      "Call `load()` from `onMounted` and from the Reload button."
    ],
  },
  {
    id: "seed-challenge-lab-vue-14-deep-watch",
    categorySlug: "vue",
    title: "Deep Watchers",
    description: `Watch nested reactive objects with deep: true.

Complete DeepWatch so nested changes to \`profile\` append a log line.`,
    difficulty: "INTERMEDIATE",
    starterCode: `<script setup lang="ts">
/**
 * Challenge: Deep watch on a nested object
 * - Watch \`profile\` deeply
 * - Push a log string whenever any nested field changes
 */
import { reactive, watch, ref } from 'vue'

export interface Profile {
  name: string
  address: {
    city: string
    zip: string
  }
}

const profile = reactive<Profile>({
  name: 'Ada',
  address: { city: 'London', zip: 'SW1' },
})

const logs = ref<string[]>([])

// TODO: watch profile with { deep: true }
// On change, push \`Changed: \${profile.name} @ \${profile.address.city}\`
watch(
  () => profile,
  () => {
    // TODO
  },
)

function rename(name: string) {
  profile.name = name
}

function move(city: string) {
  profile.address.city = city
}

defineExpose({ profile, logs, rename, move })
</script>

<template>
  <div class="deep-watch" data-testid="deep-watch">
    <p data-testid="summary">{{ profile.name }} — {{ profile.address.city }}</p>
    <ul data-testid="logs">
      <li v-for="(line, i) in logs" :key="i">{{ line }}</li>
    </ul>
    <div class="actions">
      <button type="button" data-testid="rename" @click="rename('Grace')">
        Rename
      </button>
      <button type="button" data-testid="move" @click="move('Oxford')">
        Move city
      </button>
    </div>
  </div>
</template>

<style scoped>
.actions {
  display: flex;
  gap: 0.5rem;
  margin-top: 0.75rem;
}
button {
  font: inherit;
  padding: 0.4rem 0.75rem;
  border: 1px solid var(--border);
  border-radius: 6px;
  background: var(--surface);
  color: var(--ink);
  cursor: pointer;
}
ul {
  margin: 0.5rem 0 0;
  padding-left: 1.25rem;
  color: var(--muted);
  font-size: 0.9rem;
}
</style>
`,
    solutionCode: `/** Solution sketch — DeepWatch */
watch(
  profile,
  () => {
    logs.value.push(\`Changed: \${profile.name} @ \${profile.address.city}\`)
  },
  { deep: true },
)
`,
    testCases: [
      {
        description: "__meta__",
        input: {
          runner: "vue",
          suiteId: "vue-14-deep-watch",
          filename: "14-DeepWatch.vue",
        },
        expectedOutput: true,
      },
    ],
    hints: [
      "`watch(profile, handler, { deep: true })` — or watch a getter.",
      "Push ``Changed: ${profile.name} @ ${profile.address.city}`` into `logs`."
    ],
  },
  {
    id: "seed-challenge-lab-vue-15-reactive-form",
    categorySlug: "vue",
    title: "Reactive Form Object",
    description: `Validate a reactive() form with computed flags.

Complete ReactiveForm:
- \`emailValid\` when email contains \`@\`
- \`canSubmit\` when name is non-empty and email is valid
- Reset clears both fields`,
    difficulty: "INTERMEDIATE",
    starterCode: `<script setup lang="ts">
/**
 * Challenge: reactive() form object + simple validation
 * - Keep form fields on a reactive object
 * - emailValid: includes '@'
 * - canSubmit: name non-empty AND emailValid
 */
import { reactive, computed } from 'vue'

const form = reactive({
  name: '',
  email: '',
})

// TODO
const emailValid = computed(() => false)

// TODO
const canSubmit = computed(() => false)

function reset() {
  form.name = ''
  form.email = ''
}

defineExpose({ form, emailValid, canSubmit, reset })
</script>

<template>
  <form class="form" data-testid="form" @submit.prevent>
    <label>
      Name
      <input v-model="form.name" data-testid="name" type="text" />
    </label>
    <label>
      Email
      <input v-model="form.email" data-testid="email" type="email" />
    </label>
    <p data-testid="email-valid">{{ emailValid ? 'valid' : 'invalid' }}</p>
    <button type="submit" data-testid="submit" :disabled="!canSubmit">
      Submit
    </button>
    <button type="button" data-testid="reset" @click="reset">Reset</button>
  </form>
</template>

<style scoped>
.form {
  display: flex;
  flex-direction: column;
  gap: 0.75rem;
  max-width: 22rem;
}
label {
  display: flex;
  flex-direction: column;
  gap: 0.3rem;
  font-size: 0.85rem;
  color: var(--muted);
}
input {
  font: inherit;
  padding: 0.55rem 0.75rem;
  border: 1px solid var(--border);
  border-radius: 6px;
  background: var(--surface);
  color: var(--ink);
}
button {
  font: inherit;
  padding: 0.5rem 0.85rem;
  border: 1px solid var(--border);
  border-radius: 6px;
  background: var(--surface);
  color: var(--ink);
  cursor: pointer;
}
button:disabled {
  opacity: 0.45;
  cursor: not-allowed;
}
</style>
`,
    solutionCode: `/** Solution sketch — ReactiveForm */
const emailValid = computed(() => form.email.includes('@'))

const canSubmit = computed(
  () => form.name.trim().length > 0 && emailValid.value,
)
`,
    testCases: [
      {
        description: "__meta__",
        input: {
          runner: "vue",
          suiteId: "vue-15-reactive-form",
          filename: "15-ReactiveForm.vue",
        },
        expectedOutput: true,
      },
    ],
    hints: [
      "`emailValid`: `form.email.includes(\"@\")`.",
      "`canSubmit`: name trimmed non-empty AND emailValid."
    ],
  },
  {
    id: "seed-challenge-lab-vue-16-checkbox-model",
    categorySlug: "vue",
    title: "Boolean defineModel",
    description: `Wire a checkbox with defineModel<boolean>.

Complete FancyCheckbox for \`<FancyCheckbox v-model="on" label="…" />\`.`,
    difficulty: "BEGINNER",
    starterCode: `<script setup lang="ts">
/**
 * Challenge: defineModel for a boolean checkbox
 * - v-model binds checked state
 * - Optional label prop
 */
// TODO: const checked = defineModel<boolean>({ default: false })

defineProps<{
  label?: string
}>()
</script>

<template>
  <label class="check" data-testid="check">
    <!-- TODO: <input type="checkbox" v-model="checked" data-testid="input" /> -->
    <input data-testid="input" type="checkbox" />
    <span v-if="label">{{ label }}</span>
  </label>
</template>

<style scoped>
.check {
  display: inline-flex;
  align-items: center;
  gap: 0.5rem;
  cursor: pointer;
  font: inherit;
}
</style>
`,
    solutionCode: `<!-- Solution sketch — FancyCheckbox -->
<script setup lang="ts">
const checked = defineModel<boolean>({ default: false })

defineProps<{
  label?: string
}>()
</script>

<template>
  <label class="check" data-testid="check">
    <input v-model="checked" data-testid="input" type="checkbox" />
    <span v-if="label">{{ label }}</span>
  </label>
</template>
`,
    testCases: [
      {
        description: "__meta__",
        input: {
          runner: "vue",
          suiteId: "vue-16-checkbox-model",
          filename: "16-FancyCheckbox.vue",
        },
        expectedOutput: true,
      },
    ],
    hints: [
      "`const checked = defineModel<boolean>({ default: false })`.",
      "`<input type=\"checkbox\" v-model=\"checked\" />`."
    ],
  },
  {
    id: "seed-challenge-lab-vue-17-teleport-modal",
    categorySlug: "vue",
    title: "Teleport Modal",
    description: `Render a modal into document.body with Teleport.

Complete Modal:
- Teleport overlay to \`body\` when \`open\`
- Emit \`close\` from backdrop and Close button
- Render default slot as content`,
    difficulty: "INTERMEDIATE",
    starterCode: `<script setup lang="ts">
/**
 * Challenge: Teleport a modal to document.body
 * - When \`open\` is true, render overlay + dialog via <Teleport to="body">
 * - Emit \`close\` when backdrop or Close button is clicked
 */
defineProps<{
  open: boolean
  title?: string
}>()

const emit = defineEmits<{
  close: []
}>()

function requestClose() {
  emit('close')
}
</script>

<template>
  <!--
    TODO: <Teleport to="body">
      <div v-if="open" data-testid="modal-root">
        <div class="backdrop" data-testid="backdrop" @click="requestClose" />
        <div class="dialog" data-testid="dialog" role="dialog" :aria-label="title ?? 'Dialog'">
          <header v-if="title"><h2>{{ title }}</h2></header>
          <div class="content"><slot /></div>
          <button type="button" data-testid="close" @click="requestClose">Close</button>
        </div>
      </div>
    </Teleport>
  -->
</template>

<style scoped>
.backdrop {
  position: fixed;
  inset: 0;
  background: rgb(0 0 0 / 0.45);
  z-index: 40;
}
.dialog {
  position: fixed;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  z-index: 50;
  background: var(--surface, #fff);
  color: var(--ink, #111);
  border-radius: 10px;
  padding: 1.25rem;
  min-width: 16rem;
  max-width: 90vw;
  box-shadow: 0 12px 40px rgb(0 0 0 / 0.2);
}
header h2 {
  margin: 0 0 0.75rem;
  font-size: 1.1rem;
}
.content {
  margin-bottom: 1rem;
}
button {
  font: inherit;
  padding: 0.4rem 0.75rem;
  border: 1px solid var(--border, #ccc);
  border-radius: 6px;
  background: transparent;
  cursor: pointer;
}
</style>
`,
    solutionCode: `<!-- Solution sketch — Modal with Teleport -->
<template>
  <Teleport to="body">
    <div v-if="open" data-testid="modal-root">
      <div class="backdrop" data-testid="backdrop" @click="requestClose" />
      <div
        class="dialog"
        data-testid="dialog"
        role="dialog"
        :aria-label="title ?? 'Dialog'"
      >
        <header v-if="title">
          <h2>{{ title }}</h2>
        </header>
        <div class="content">
          <slot />
        </div>
        <button type="button" data-testid="close" @click="requestClose">Close</button>
      </div>
    </div>
  </Teleport>
</template>
`,
    testCases: [
      {
        description: "__meta__",
        input: {
          runner: "vue",
          suiteId: "vue-17-teleport-modal",
          filename: "17-Modal.vue",
        },
        expectedOutput: true,
      },
    ],
    hints: [
      "`<Teleport to=\"body\"><div v-if=\"open\" …>`",
      "Backdrop and Close should `emit(\"close\")`."
    ],
  },
  {
    id: "seed-challenge-lab-vue-18-transition",
    categorySlug: "vue",
    title: "Fade Transition",
    description: `Animate enter/leave with <Transition>.

Wrap the panel in \`<Transition name="fade">\` and show it with \`v-if="visible"\`.`,
    difficulty: "INTERMEDIATE",
    starterCode: `<script setup lang="ts">
/**
 * Challenge: Transition — fade a panel in/out
 * - \`visible\` controls whether the panel is shown
 * - Wrap with <Transition name="fade">
 */
defineProps<{
  visible: boolean
}>()
</script>

<template>
  <div class="fade-demo" data-testid="fade-demo">
    <!-- TODO: <Transition name="fade"><div v-if="visible" class="panel" data-testid="panel"><slot /></div></Transition> -->
  </div>
</template>

<style scoped>
.panel {
  padding: 1rem;
  border: 1px solid var(--border);
  border-radius: 8px;
  background: var(--surface);
}

.fade-enter-active,
.fade-leave-active {
  transition: opacity 0.2s ease;
}
.fade-enter-from,
.fade-leave-to {
  opacity: 0;
}
</style>
`,
    solutionCode: `<!-- Solution sketch — FadeToggle -->
<template>
  <div class="fade-demo" data-testid="fade-demo">
    <Transition name="fade">
      <div v-if="visible" class="panel" data-testid="panel">
        <slot>Hello</slot>
      </div>
    </Transition>
  </div>
</template>
`,
    testCases: [
      {
        description: "__meta__",
        input: {
          runner: "vue",
          suiteId: "vue-18-transition",
          filename: "18-FadeToggle.vue",
        },
        expectedOutput: true,
      },
    ],
    hints: [
      "`<Transition name=\"fade\"><div v-if=\"visible\" …>`",
      "CSS classes `.fade-enter-active` etc. are already provided."
    ],
  },
  {
    id: "seed-challenge-lab-vue-19-local-storage",
    categorySlug: "vue",
    title: "Composable: useLocalStorage",
    description: `Build a composable that keeps a ref in sync with localStorage across reloads.

Build \`useLocalStorage(key, initial)\` — a composable that makes any JSON-serializable value survive page reloads.

Why: components often need settings or drafts to persist. Instead of calling localStorage in every component, wrap it once (same idea as useToggle).

API example:
  const { value, clear } = useLocalStorage('theme', 'light')
  value.value = 'dark'   // also writes to localStorage
  clear()                // back to 'light', key removed

Behaviour:
1. Key missing in localStorage → start from \`initial\`
2. Key exists → JSON.parse it (if parse fails, use \`initial\`)
3. Whenever \`value\` changes → JSON.stringify + setItem
4. clear() → reset value to \`initial\`, then removeItem so the key is gone

Tips:
- Generic <T> so it works for numbers, strings, objects, …
- watch with { deep: true } so nested object edits are saved
- Prefer flush: 'sync' so the write happens immediately (not next tick)`,
    difficulty: "ADVANCED",
    starterCode: `import { ref, watch, type Ref } from 'vue'

/**
 * Challenge: useLocalStorage
 *
 * A composable that mirrors a reactive value to \`localStorage\`.
 *
 * Usage:
 *   const { value, clear } = useLocalStorage('count', 0)
 *   value.value++        // persisted automatically
 *   clear()              // reset to 0 and remove the storage key
 *
 * Requirements:
 * 1. Read existing JSON for \`key\` on init; fall back to \`initial\` if missing/invalid
 * 2. Return a Ref that stays in sync — every change is stringified and saved
 * 3. \`clear()\` restores \`initial\` and deletes the key from localStorage
 */
export function useLocalStorage<T>(
  key: string,
  initial: T,
): { value: Ref<T>; clear: () => void } {
  // TODO: implement
  void ref
  void watch
  void key
  void initial
  throw new Error('Not implemented')
}
`,
    solutionCode: `import { ref, watch, type Ref } from 'vue'

/** Solution — useLocalStorage */
export function useLocalStorage<T>(
  key: string,
  initial: T,
): { value: Ref<T>; clear: () => void } {
  let start = initial
  const raw = localStorage.getItem(key)
  if (raw != null) {
    try {
      start = JSON.parse(raw) as T
    } catch {
      start = initial
    }
  }

  const value = ref(start) as Ref<T>

  watch(
    value,
    (v) => {
      localStorage.setItem(key, JSON.stringify(v))
    },
    { deep: true, flush: 'sync' },
  )

  function clear() {
    value.value = initial
    localStorage.removeItem(key)
  }

  return { value, clear }
}
`,
    testCases: [
      {
        description: "__meta__",
        input: {
          runner: "vue",
          suiteId: "vue-19-local-storage",
          filename: "19-useLocalStorage.ts",
        },
        expectedOutput: true,
      },
    ],
    hints: [
      "On create: `const raw = localStorage.getItem(key)`. If it’s null, use `initial`. Otherwise `JSON.parse(raw)` (fall back to `initial` if parse fails).",
      "Create `const value = ref(start)` and `watch(value, (v) => localStorage.setItem(key, JSON.stringify(v)), { deep: true, flush: \"sync\" })`. `deep` covers objects; `flush: \"sync\"` writes immediately so tests (and callers) see storage right away.",
      "`clear()`: set `value.value = initial` first (the watcher will rewrite storage), then `localStorage.removeItem(key)` so the key ends up deleted."
    ],
  },
  {
    id: "seed-challenge-lab-vue-20-notes",
    categorySlug: "vue",
    title: "Notes App",
    description: `Capstone: create, select, edit, search, and delete notes.

Build NotesApp:
- Add note (non-empty title), clear drafts, select new note
- Edit title/body of selection in place
- Search filters list by title
- Delete selection and show empty state


Playground: /playground/notes`,
    difficulty: "ADVANCED",
    starterCode: `<script setup lang="ts">
/**
 * Challenge: Notes App (capstone)
 *
 * Requirements:
 * - Add a note from title + body (ignore empty title)
 * - Select a note to view/edit
 * - Update selected note's title/body
 * - Delete selected note
 * - Search filters by title (case-insensitive)
 * - Show count of notes
 */
import { ref, computed } from 'vue'

export interface Note {
  id: number
  title: string
  body: string
}

const notes = ref<Note[]>([])
const selectedId = ref<number | null>(null)
const draftTitle = ref('')
const draftBody = ref('')
const query = ref('')

let nextId = 1

const selected = computed(() => {
  // TODO: find note by selectedId
  return null as Note | null
})

const visible = computed((): Note[] => {
  // TODO: filter notes by query (trim, case-insensitive title match)
  return notes.value
})

function addNote() {
  // TODO: create note from drafts, select it, clear drafts
  void nextId
}

function selectNote(id: number) {
  // TODO
  void id
}

function updateSelected() {
  // TODO: write selected.title/body from drafts (or edit fields bound to selected)
}

function removeSelected() {
  // TODO: delete selected; clear selection
}

defineExpose({
  notes,
  selectedId,
  selected,
  visible,
  draftTitle,
  draftBody,
  query,
  addNote,
  selectNote,
  updateSelected,
  removeSelected,
})
</script>

<template>
  <div class="notes" data-testid="notes">
    <aside class="sidebar">
      <form class="add" @submit.prevent="addNote">
        <input
          v-model="draftTitle"
          data-testid="new-title"
          type="text"
          placeholder="Title"
          aria-label="New note title"
        />
        <textarea
          v-model="draftBody"
          data-testid="new-body"
          placeholder="Body"
          aria-label="New note body"
          rows="2"
        />
        <button type="submit" data-testid="add">Add note</button>
      </form>

      <input
        v-model="query"
        data-testid="search"
        type="search"
        placeholder="Search titles…"
        aria-label="Search notes"
      />

      <ul data-testid="list">
        <li
          v-for="note in visible"
          :key="note.id"
          :data-testid="\`note-\${note.id}\`"
          :class="{ active: note.id === selectedId }"
        >
          <button type="button" @click="selectNote(note.id)">
            {{ note.title }}
          </button>
        </li>
      </ul>
      <p class="count" data-testid="count">{{ notes.length }} notes</p>
    </aside>

    <section class="editor" data-testid="editor">
      <template v-if="selected">
        <input
          v-model="selected.title"
          data-testid="edit-title"
          type="text"
          aria-label="Edit title"
        />
        <textarea
          v-model="selected.body"
          data-testid="edit-body"
          rows="8"
          aria-label="Edit body"
        />
        <button type="button" data-testid="delete" @click="removeSelected">
          Delete
        </button>
      </template>
      <p v-else data-testid="empty">Select or create a note</p>
    </section>
  </div>
</template>

<style scoped>
.notes {
  display: grid;
  grid-template-columns: minmax(12rem, 16rem) 1fr;
  gap: 1rem;
  min-height: 20rem;
}
.sidebar,
.editor {
  border: 1px solid var(--border);
  border-radius: 10px;
  padding: 0.85rem;
  background: var(--surface);
}
.add {
  display: flex;
  flex-direction: column;
  gap: 0.4rem;
  margin-bottom: 0.75rem;
}
input,
textarea,
button {
  font: inherit;
}
input,
textarea {
  padding: 0.45rem 0.6rem;
  border: 1px solid var(--border);
  border-radius: 6px;
  background: var(--paper, #fff);
  color: var(--ink);
  width: 100%;
  box-sizing: border-box;
}
button {
  padding: 0.4rem 0.7rem;
  border: 1px solid var(--border);
  border-radius: 6px;
  background: var(--surface-2, #f3f3f3);
  color: var(--ink);
  cursor: pointer;
}
ul {
  list-style: none;
  margin: 0.75rem 0;
  padding: 0;
  display: flex;
  flex-direction: column;
  gap: 0.25rem;
}
li button {
  width: 100%;
  text-align: left;
  background: transparent;
}
li.active button {
  background: var(--ink);
  color: var(--paper, #fff);
  border-color: var(--ink);
}
.editor {
  display: flex;
  flex-direction: column;
  gap: 0.6rem;
}
.count {
  margin: 0;
  font-size: 0.85rem;
  color: var(--muted);
}
@media (max-width: 640px) {
  .notes {
    grid-template-columns: 1fr;
  }
}
</style>
`,
    solutionCode: `/** Solution sketch — NotesApp */
const selected = computed(
  () => notes.value.find((n) => n.id === selectedId.value) ?? null,
)

const visible = computed(() => {
  const q = query.value.trim().toLowerCase()
  if (!q) return notes.value
  return notes.value.filter((n) => n.title.toLowerCase().includes(q))
})

function addNote() {
  const title = draftTitle.value.trim()
  if (!title) return
  const note = { id: nextId++, title, body: draftBody.value }
  notes.value.push(note)
  selectedId.value = note.id
  draftTitle.value = ''
  draftBody.value = ''
}

function selectNote(id: number) {
  selectedId.value = id
}

function removeSelected() {
  if (selectedId.value == null) return
  notes.value = notes.value.filter((n) => n.id !== selectedId.value)
  selectedId.value = null
}
`,
    testCases: [
      {
        description: "__meta__",
        input: {
          runner: "vue",
          suiteId: "vue-20-notes",
          filename: "20-NotesApp.vue",
        },
        expectedOutput: true,
      },
    ],
    hints: [
      "Keep notes in a ref array; `selectedId` points at the active note.",
      "`selected` computed returns the note object so the editor can v-model its fields.",
      "Filter with `title.toLowerCase().includes(query.trim().toLowerCase())`."
    ],
  }
];
